@startuml
title <size:24>FkmedApplication</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("FkmedApplication_boundary", "FkmedApplication", $tags="") {
  Container_Boundary("FkmedApplication.FkmedApplication_boundary", "FkmedApplication", $tags="") {
    Component(FkmedApplication.FkmedApplication.identity, "identity", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.card, "card", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.clinicaldocs, "clinicaldocs", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.guides, "guides", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.support, "support", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.telemedicine, "telemedicine", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.notification, "notification", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.audit, "audit", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.errorkernel, "error kernel", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.network, "network", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.plan, "plan", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.appointment, "appointment", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.finance, "finance", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(FkmedApplication.FkmedApplication.appointment, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.appointment, FkmedApplication.FkmedApplication.network, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.appointment, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.card, FkmedApplication.FkmedApplication.audit, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.card, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.card, FkmedApplication.FkmedApplication.identity, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.card, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.clinicaldocs, FkmedApplication.FkmedApplication.audit, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.clinicaldocs, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.clinicaldocs, FkmedApplication.FkmedApplication.identity, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.clinicaldocs, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.finance, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.finance, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.guides, FkmedApplication.FkmedApplication.audit, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.guides, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.guides, FkmedApplication.FkmedApplication.identity, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.guides, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.identity, FkmedApplication.FkmedApplication.audit, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.identity, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.identity, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.network, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.appointment, "listens to", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.clinicaldocs, "listens to", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.finance, "listens to", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.guides, "listens to", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.identity, "listens to", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.identity, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.plan, "listens to", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.notification, FkmedApplication.FkmedApplication.telemedicine, "listens to", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.plan, FkmedApplication.FkmedApplication.audit, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.plan, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.support, FkmedApplication.FkmedApplication.audit, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.support, FkmedApplication.FkmedApplication.identity, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.support, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.telemedicine, FkmedApplication.FkmedApplication.appointment, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.telemedicine, FkmedApplication.FkmedApplication.clinicaldocs, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.telemedicine, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.telemedicine, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml