@startuml
title <size:24>FkmedApplication</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("FkmedApplication_boundary", "FkmedApplication", $tags="") {
  Container_Boundary("FkmedApplication.FkmedApplication_boundary", "FkmedApplication", $tags="") {
    Component(FkmedApplication.FkmedApplication.audit, "audit", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.errorkernel, "error kernel", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.plan, "plan", $techn="Module", $descr="", $tags="", $link="")
    Component(FkmedApplication.FkmedApplication.identity, "identity", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(FkmedApplication.FkmedApplication.identity, FkmedApplication.FkmedApplication.plan, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.identity, FkmedApplication.FkmedApplication.audit, "uses", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.plan, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")
Rel(FkmedApplication.FkmedApplication.identity, FkmedApplication.FkmedApplication.errorkernel, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml